### ISSUE TITLE
What happened to 0.3.27 and 0.3.26?

### ISSUE THREAD

**Issue by zoltan-fedor** [taichino/croniter#124]
Hey,
I came here from PyPI after one of our deployments complained about croniter 0.3.27 is no longer being available on PyPI.
What happened?
Why that earlier recent 8 days old version was pulled suddenly?
Thanks

**Comment by artem-panchenko** [comment]
Same question about `0.3.26`.

**Comment by gerardo-orozco** [comment]
and `0.3.21`...
what is the reasoning behind removing older releases from pypi?

**Comment by DiggidyDave** [comment]
Removing releases is a no-no. Can we depend on this library going forward?

**Comment by alanjcastonguay** [comment]
Also had builds fail today, with 0.3.27 pinned. https://github.com/taichino/croniter/issues/119 is where https://pypi.org/project/croniter/0.3.27/ was stated released. @kiorky what happened here?

**Comment by efokschaner** [comment]
This line of this commit (https://github.com/kiorky/croniter/commit/b57519eba539ac296d64fc7d16ce6ee88f0d28ff#diff-b6190f052518a40f7418a056047abbd3R8) makes me wonder if there was some kind of intentional history re-write / unpublish which raises more questions that it answers.

**Comment by alanjcastonguay** [comment]
I haven't found any mention of 0.3.27 in commit history; was there also a force push?

**Comment by fbpcchen** [comment]
Plz tell me what happened to 0.3.27 ！！！

**Comment by ojhilt** [comment]
Deleting old versions can have serious consequences on deployments and while this thankfully hasn't caused us any downtime it could have over a long weekend or something like that.  PLEASE respect the community and DO NOT delete old releases, this is one of the major causes of problems in Python in general and ideally should be prevented at the PyPi level.

**Comment by kiorky** [comment]
security pb in readme, you have to upgrade to new release.

**Comment by kiorky** [comment]
I tried to reupload fixed tarballs to pypi but its can't be done anymore (see their tracker, it's "on purpose") ...

**Comment by DiggidyDave** [comment]
@kiorky any chance you can speak to what happened here before closing?

**Comment by kiorky** [comment]
You can find fixed artefacts for both versions:
- [0.3.27](https://github.com/kiorky/croniter/releases/tag/0.3.27)
- [0.3.26](https://github.com/kiorky/croniter/releases/tag/0.3.26)

**Comment by kiorky** [comment]
@gerardo-orozco 0.3.21 never existed.

**Comment by surbas** [comment]
Sorry having trouble finding the "security pb". What was the security issue?

**Comment by kiorky** [comment]
information leak; no problem in the library itself.

**Comment by kiorky** [comment]
Repost of my previous comment to be very clear:
- 0.3.29 has only a rewrotten README, no code change in the library from what was in 0.3.27.
- I though that was clear by the changelog entry
- Pypi lets you delete artefacts, but the problem is that it was a time you could reupload artefacts, it's impossible for now. What's funny is that i was trapped becaused the delete was already done. I dont understand their reasonning, release must not be touched at any cost, at 99%, but there are still legit use cases to do it. For further details, you can search for the issue 74 in "github/pypa/packaging-problems" (not putting a direct link on purpose).

You can find fixed artefacts for both versions:
- [0.3.27](https://github.com/kiorky/croniter/releases/tag/0.3.27)
- [0.3.26](https://github.com/kiorky/croniter/releases/tag/0.3.26)

**Comment by DiggidyDave** [comment]
Thanks for the info!
